### ISSUE TITLE
Suggestion: onSelected

### ISSUE THREAD

**Issue by ghost** [fgcan10/selectable_container#1]
Hi. This widget a good idea because Container is a handy widget and turn it selectable, makes it more useful. And I'd suggest a little change, that i needed to do when i used it:

1) Create a field **ValueChanged<bool> onSelected** (or replace the onPressed):

```
...
  /// Notifies that [select] has changed
  final ValueChanged<bool> onSelected;

SelectableContainer(
      {this.selected,
      @required this.onSelected,
...
```

2) Create the folowing method:

```
 void _handleTap() {
    widget.onSelected(!widget.selected);
  } 
```

3) Modifiy the code like bellow:

```
 return GestureDetector(
      // onTap: () {
      //   setState(() {
      //     widget.selected = !widget.selected;
      //   });
      //   // widget.onPressed();
      // },
      onTap: () => _handleTap(),
```

4) And then you can use the widget like other selectable widgets such as CheckBox, RadioButton, Chips, etc.

```
return SelectableContainer(
    selected: something == otherthing,
    onSelected: (selected) {
              setState(() {
                   //Do something case 'selected' equals true or false
              });
   });
```

**Comment by fgcan10** [comment]
Hi, thank you for the tip! I also think it's a good idea.
I'll implement it in the next version.

**Comment by ghost** [comment]
Nice! I was using the container inside a list. And with onPressed it's possible select many at the same time. With onSelected just one each time. Perhaps you can use both, and turn optional the use with single or multiple selections.
