### ISSUE TITLE
Background image in container

### ISSUE THREAD

**Issue by Entrebear** [fgcan10/selectable_container#10]
Hi

In the demo image it shows containers with images in the containers.

I only see an option to set the background colour, how do I put an image in the container?

Thanks

**Comment by fgcan10** [comment]
Hi,

Thanks for having a look at the package. 
To add an image or any other content you can use the 'child' option. In the example project included in the package you can see how I do it.

Here another example : 
SelectableContainer(
        selectedBackgroundColorIcon: Theme.of(context).dialogBackgroundColor,
        unselectedBackgroundColorIcon: Theme.of(context).dialogBackgroundColor,
        unselectedIcon: Icons.check_box_outline_blank,
        icon: Icons.check_box,
        iconAlignment: Alignment.topRight,
        iconSize: 24,
        iconColor: Colors.deepOrange[400]!,
        onValueChanged: (_) {
          _valueSelected(i);
        },
        topMargin: 5.0,
        leftMargin: 10.0,
        rightMargin: 10.0,
        bottomMargin: 10.0,
        child: SizedBox(
          height: 100,
          width: 100,
          child: Image.asset(
            'images/dog1.jpg',
            fit: BoxFit.fitWidth,
          ),
        ),
      ));
