### ISSUE TITLE
No option to set margin - space between containers.

### ISSUE THREAD

**Issue by markbulingit** [fgcan10/selectable_container#7]
I think we should provide options to customize margin -spacing between cards, it's too big on my design case.
Your package is awesome btw.

![image](https://user-images.githubusercontent.com/91706339/154738370-26c311b1-cac0-4a2f-880a-25dbd5351238.png)

**Comment by fgcan10** [comment]
Hi, 

Thank you for using the package! And thank you for sending an image, nice to see it in action!!

I'll have a look at it and let you know.

**Comment by fgcan10** [comment]
See version 1.0.3 of the package
